### PR TITLE
Changes for adding ppc64le support

### PR DESCRIPTION
**Pull request by seth-priya**
Reference : https://github.com/ManageIQ/manageiq/issues/19676

### CODE REVIEW

**Comment by seth-priya** [comment]
@bdunne thanks for your comments on https://github.com/ManageIQ/container-ruby/pull/16 , I could not re-open the original PR, so created this for further discussion. Apologies for going back and forth.

Regarding your comment about creating the ppc64le RPMs, is there a specific repository/script or CI (Travis?) job that currently creates the Intel RPMs that I can try to emulate and test on Power?

**Comment by carbonin** [comment]
The rpm is hosted here https://copr-be.cloud.fedoraproject.org/results/manageiq/ManageIQ-Master/epel-7-x86_64/00912593-ruby-install/ which is built using COPR here https://copr.fedorainfracloud.org/coprs/manageiq/ManageIQ-Master/build/912593/

It is technically a `noarch` rpm so we should be able to just create a separate repo for non-arch specific rpms and share it, right @simaishi ?

**Comment by simaishi** [comment]
> It is technically a `noarch` rpm so we should be able to just create a separate repo for non-arch specific rpms and share it, right @simaishi ?

Yes, I think that's what we should do. I'll take a look.

**Comment by simaishi** [comment]
@seth-priya please test the rpm using https://copr.fedorainfracloud.org/coprs/simaishi/test/repo/epel-7/simaishi-test-epel-7.repo

If it looks good, I'll make the RPM available in manageiq/ManageIQ-Master.

**Comment by seth-priya** [comment]
thanks @simaishi I will test it and let you know

**Comment by seth-priya** [comment]
@simaishi everything looks good

1. change to the up-stream dockerfile
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 24b196c..6dc9987 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,7 +7,7 @@ ENV RUBY_GEMS_ROOT=/usr/local/lib/ruby/gems/2.5.0 \

 \# Install repos
 RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
-    curl -sL https://copr.fedorainfracloud.org/coprs/manageiq/ManageIQ-Master/repo/epel-7/manageiq-ManageIQ-Master-epel-7.repo -o /etc/yum.repos.d/manageiq.repo
+    curl -sL https://copr.fedorainfracloud.org/coprs/simaishi/test/repo/epel-7/simaishi-test-epel-7.repo -o /etc/yum.repos.d/manageiq.repo

\# Install ruby-install and make
 RUN yum -y install --setopt=tsflags=nodocs ruby-install make

2. The image was built successfully on a Power (ppc64le)/RHEL 7.6 host
$ docker images | grep ruby
manageiq/ruby                                                                                                     2.5                         2687ab5b0efb        3 hours ago         572MB

3. The image runs successfully and ruby, ruby-install versions all look correct
$ docker run -it manageiq/ruby:2.5 bash
[root@767b79c38d99 /]# uname -a
Linux 767b79c38d99 3.10.0-1062.el7.ppc64le #1 SMP Thu Jul 18 20:29:07 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
[root@767b79c38d99 /]# ruby --version
ruby 2.5.7p206 (2019-10-01 revision 67816) [powerpc64le-linux]
[root@767b79c38d99 /]# ruby-install --version
ruby-install: 0.7.0

4. Build logs
Attached

[container-ruby-build-with-RPM-logs.txt](https://github.com/ManageIQ/container-ruby/files/4044401/container-ruby-build-with-RPM-logs.txt)

Please do let me know if further testing is required and thanks a lot for pulling this together and creating the RPM, I believe we can close the PR once the RPM is published.

Thank you again !!

**Comment by simaishi** [comment]
@seth-priya Thank you for testing 😄  The RPM is now available in manageiq/ManageIQ-Master.

**Comment by carbonin** [comment]
Now that @simaishi has added the package to the existing repo, does the build work without changes?

i.e. Can we close this PR now?

**Comment by seth-priya** [comment]
@simaishi @carbonin thanks a lot!! yes this now builds without issues on ppc64le, closing the PR. Thank you, again!!

**Pull request closed without merging**
